title: Rino Cattabiani
logo: assets/id_photo.png
description: I am a recent graduate of the University of Connecticut, where I earned a Master of Science in Quantitative Economics and Econometrics. 
theme: jekyll-theme-minimal
